run:
  build-tags:
    - build
    - containers_image_openpgp
  timeout: 10m

linters:
  enable:
    - errcheck
    - goimports
    - gofmt
    - gosec
    - gocritic
    - deadcode
    - misspell
    - revive
