version: "2"
run:
  timeout: 10m
  build-tags:
    - build
    - containers_image_openpgp
linters:
  settings:
    revive:
      rules:
        - name: dot-imports
          disabled: true
    staticcheck:
      checks: [ "all", "-ST1005" ]
  enable:
    - gocritic
    - gosec
    - misspell
    - errcheck
    - gosec
    - revive
    - unused
    - staticcheck
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
