version: "2"
run:
  timeout: 10m
  build-tags:
    - build
    - containers_image_openpgp
linters:
  enable:
    - gocritic
    - gosec
    - misspell
    - errcheck
    - gosec
    - revive
  disable:
    - dotimports
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
