version: "2"
run:
  build-tags:
    - build
    - containers_image_openpgp
linters:
  enable:
    - gocritic
    - gosec
    - misspell
    - errcheck
    - gofmt
    - gosec
    - goimports
    # - revive  # revive is flagging ginkgo and gomega dot-imports
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
