= CodeReady Containers - OpenShift 4 on your Laptop
:icons:
:toc: macro
:toc-title:
:toclevels:

toc::[]

image:https://travis-ci.org/code-ready/crc.svg?branch=master["Travis CI Build Status", link="https://travis-ci.org/code-ready/crc"]
image:https://circleci.com/gh/code-ready/crc/tree/master.svg?style=svg["CircleCI Build Status", link="https://circleci.com/gh/code-ready/crc"]

[[intro-to-crc]]
== Introduction

This project is focused on bringing a minimal http://github.com/openshift/origin[OpenShift 4.0 or newer] cluster to your local laptop or desktop computer. 

If you are looking for a solution for running OpenShift 3.x, you will need tools such as `oc cluster up`, http://github.com/minishift/minishift[Minishift] or https://developers.redhat.com/products/cdk/overview/[CDK].

Check back for updates, we plan to have something available "soon".

[[documentation]]
== Documentation

=== Using CodeReady Containers

You can find the source files for the documentation in the link:./docs/source[docs/source] directory.

To build the formatted documentation, use the following:

```bash
$ git clone https://github.com/code-ready/crc
$ cd crc
$ make build_docs
```

This will create a [filename]`docs/build/master.html` file which you can view in your browser.

=== Developing CodeReady Containers

Developers who want to work on CodeReady Containers should visit the link:./developing.adoc[Developing CodeReady Containers] document.

[[community]]
== Community

Contributions, questions, and comments are all welcomed and encouraged!

You can reach the community by:

- Joining the #codeready channel on https://freenode.net/[Freenode IRC]

If you want to contribute, make sure to follow the link:CONTRIBUTING.adoc[contribution guidelines]
when you open issues or submit pull requests.
