= CRC - Runs Containers
:icons:
:toc: macro
:toc-title:
:toclevels:

toc::[]

image:https://github.com/crc-org/crc/actions/workflows/make-check.yml/badge.svg?branch=main["main", link="https://github.com/crc-org/crc/actions/workflows/make-check.yml"]
image:https://github.com/crc-org/crc/actions/workflows/windows-installer.yml/badge.svg["win msi", link="https://github.com/crc-org/crc/actions/workflows/windows-installer.yml"]
image:https://github.com/crc-org/crc/actions/workflows/macos-installer.yml/badge.svg["macos pkg", link="https://github.com/crc-org/crc/actions/workflows/macos-installer.yml"]
image:https://github.com/crc-org/crc/actions/workflows/make-rpm.yml/badge.svg["rpm", link="https://github.com/crc-org/crc/actions/workflows/make-rpm.yml"]
image:https://github.com/crc-org/crc/actions/workflows/make-check-win.yml/badge.svg["win", link="https://github.com/crc-org/crc/actions/workflows/make-check-win.yml"]

[[intro-to-crc]]
== Introduction

`crc` is a tool to run containers.
It manages a local https://github.com/openshift/origin[OpenShift 4.x] cluster, or an https://github.com/openshift/okd[OKD] cluster VM optimized for testing and development purposes.

If you are looking for a solution for running OpenShift 3.x, you will need tools such as `oc cluster up`, http://github.com/minishift/minishift[Minishift] or https://developers.redhat.com/products/cdk/overview/[CDK].

[[usage-data]]
== Usage data

The first time CRC is run, you will be asked to opt-in to Red Hat's telemetry collection program.

With your approval, CRC collects pseudonymized usage data and sends it to Red Hat servers to help improve our products and services.
Read our https://developers.redhat.com/article/tool-data-collection[privacy statement] to learn more about it.
For the specific data points being collected, see xref:usage-data.adoc#data-table[Usage data].

=== Manually configuring usage data collection

You can manually change your preference about usage data collection by running `crc config set consent-telemetry <yes/no>` before the next `crc start`.

[[documentation]]
== Documentation

=== Getting CRC

CRC binaries with an embedded OpenShift disk image can be downloaded from link:https://console.redhat.com/openshift/create/local[this page].

=== Using CRC

The documentation for CRC is currently hosted by GitHub Pages.

See the link:https://crc-org.github.io/crc/[CRC Getting Started Guide].

=== Building the documentation

You can find the source files for the documentation in the link:./docs[docs] directory.

To build the formatted documentation, link:https://github.com/containers/libpod/blob/master/install.md[install podman] then use the following:

```bash
$ git clone https://github.com/crc-org/crc
$ cd crc
$ make build_docs
```

This will create a [filename]`docs/build/master.html` file which you can view in your browser.

=== Developing CRC

Developers who want to work on CRC should visit the link:./developing.adoc[Developing CRC] document.

[[community]]
== Community

Contributions, questions, and comments are all welcomed and encouraged!

You can reach the community by:

- Joining the #codeready channel on https://freenode.net/[Freenode IRC]

If you want to contribute, make sure to follow the link:CONTRIBUTING.adoc[contribution guidelines]
when you open issues or submit pull requests.
