[id="differences-from-production-openshift-install_{context}"]
= Differences from a production OpenShift installation

{rh-prod} provides a regular OpenShift installation with the following notable differences:

* **The {prod} OpenShift cluster is ephemeral and is not intended for production use.**
* **{prod} does not have a supported upgrade path to newer OpenShift versions.**
Upgrading the OpenShift version may cause issues that are difficult to reproduce.
* It uses a single node which behaves as both a control plane and worker node.
* It disables the Cluster Monitoring Operator by default.
This disabled Operator causes the corresponding part of the web console to be non-functional.
* The OpenShift cluster runs in a virtual machine known as an __instance__.
This may cause other differences, particularly with external networking.

The OpenShift cluster provided by {prod} also includes the following non-customizable cluster settings.
These settings should not be modified:

* Use of the ***.crc.testing** domain.
* The address range used for internal cluster communication.
** The cluster uses the **172** address range.
This can cause issues when, for example, a proxy is run in the same address space.
