[id="starting-codeready-containers-behind-proxy_{context}"]
= Starting {prod} behind a proxy

.Prerequisites

* To use an existing [command]`oc` binary on your host machine, export the `.testing` domain as part of the `no_proxy` environment variable.

* The embedded [command]`oc` binary does not require manual settings.
For more information about using the embedded [command]`oc` binary, see link:{crc-gsg-url}#accessing-the-openshift-cluster-with-oc_gsg[Accessing the OpenShift cluster with `oc`].


.Procedure

. Define a proxy using the `http_proxy` and `https_proxy` environment variables or using the [command]`{bin} config set` command as follows:
+
[subs="+quotes,attributes"]
----
$ {bin} config set http-proxy http://proxy.example.com:__<port>__
$ {bin} config set https-proxy http://proxy.example.com:__<port>__
$ {bin} config set no-proxy __<comma-separated-no-proxy-entries>__
----

. If the proxy uses a custom CA certificate file, set it as follows:
+
[subs="+quotes,attributes"]
----
$ {bin} config set proxy-ca-file __<path-to-custom-ca-file>__
----

The [command]`{bin}` binary will be able to use the defined proxy once set through environment variables or {prod} configuration.

[NOTE]
====
* Proxy-related values set in the configuration for {prod} have priority over values set through environment variables.
* SOCKS proxies are not supported by OpenShift Container Platform.
====
