[id="accessing-the-openshift-web-console_{context}"]
= Accessing the OpenShift web console

Access the OpenShift web console by using your web browser.

Access the cluster by using either the `kubeadmin` or `developer` user.
Use the `developer` user for creating projects or OpenShift applications and for application deployment.
Use the `kubeadmin` user only for administrative tasks such as creating new users or setting roles.

.Prerequisites

* A running {prod} virtual machine.
For more information, see link:{crc-gsg-url}#starting-the-virtual-machine_gsg[Starting the virtual machine].

.Procedure

. To access the OpenShift web console with your default web browser, run the following command:
+
[subs="+quotes,attributes"]
----
$ {bin} console
----

. Log in as the `developer` user with the password printed in the output of the [command]`{bin} start` command.
You can also view the password for the `developer` and `kubeadmin` users by running the following command:
+
[subs="+quotes,attributes"]
----
$ {bin} console --credentials
----

See link:{crc-gsg-url}#troubleshooting-codeready-containers_gsg[Troubleshooting {prod}] if you cannot access the {prod} OpenShift cluster.

.Additional resources

* The link:https://docs.openshift.com/container-platform/latest/applications/projects/working-with-projects.html[OpenShift documentation] covers the creation of projects and applications.
