[id="deploying-sample-application-with-odo_{context}"]
= Deploying a sample application with `odo`

You can use [command]`odo` to create {openshift} projects and applications from the command line.
This procedure deploys a sample application to the {ocp} cluster running in the {prod} instance.

.Prerequisites

* You have installed [command]`odo`.
For more information, see link:{odo-docs-url-installing}[Installing `odo`] in the [command]`odo` documentation.
* {prod} is configured to use the {openshift} preset.
For more information, see link:{crc-gsg-url}#changing-the-selected-preset_gsg[Changing the selected preset].
* The {prod} instance is running.
For more information, see link:{crc-gsg-url}#starting-the-instance_gsg[Starting the instance].

.Procedure

. Log in to the running {ocp} cluster managed by {prod} as the `developer` user:
+
[subs="+quotes,attributes"]
----
$ odo login -u developer -p developer
----

. Create a project for your application:
+
[subs="+quotes,attributes"]
----
$ odo create project sample-app
----

. Create a directory for your components:
+
[subs="+quotes,attributes"]
----
$ mkdir sample-app
$ cd sample-app
----

. Bootstrap a Node.js component and download a starter project:
+
[subs="+quotes,attributes"]
----
$ odo init --name sample-app --devfile nodejs --starter nodejs-starter
----

. Developing the `nodejs` application continuously:
+
[subs="+quotes,attributes"]
----
$ odo dev
----
+
You can now access the application in your local browser using the URL from the output of the above command and start your development loop.
[command]`odo` will watch for changes and push the code for real-time updates.

.Additional resources

* For more information about using [command]`odo`, see the link:{odo-docs-url}[`odo` documentation].
