[id="installing-codeready-containers_{context}"]
= Installing {prod}

{prod} is available as a portable executable for {rhel} and {msw}.
On {mac}, {prod} is available using a guided installer.

.Prerequisites

* Your host machine must meet the minimum system requirements.
For more information, see link:{crc-gsg-url}#minimum-system-requirements_gsg[Minimum system requirements].

.Procedure

. Download the link:{crc-download-url}[latest release of {prod}] for your platform.

. On {msw}, extract the contents of the archive.

. On {mac} or {msw}, run the guided installer and follow the instructions.
+
[NOTE]
====
On {msw}, you must install {prod} to your local [filename]*_C:\_* drive.
You cannot run {prod} from a network drive.
====
+
On {rhel}, assuming the archive is in the [filename]*_~/Downloads_* directory, follow these steps:
+
.. Extract the contents of the archive:
+
[subs="attributes"]
----
$ cd ~/Downloads
$ tar xvf crc-linux-amd64.tar.xz
----
+
.. Create the [filename]*_~/bin_* directory if it does not exist and copy the [command]`{bin}` executable to it:
+
[subs="attributes"]
----
$ mkdir -p ~/bin
$ cp ~/Downloads/crc-linux-*-amd64/{bin} ~/bin
----
+
.. Add the [filename]*_~/bin_* directory to your `$PATH`:
+
[subs="attributes"]
----
$ export PATH=$PATH:$HOME/bin
$ echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
----
