[id="setting-up-codeready-containers_{context}"]
= Setting up {prod}

The [command]`{bin} setup` command performs operations to set up the environment of your host machine for the {prod} virtual machine.

This procedure creates the [filename]*_~/.crc_* directory if it does not already exist.

[WARNING]
====
If you are setting up a new version, capture any changes made to the virtual machine before setting up a new {prod} release.
====

.Prerequisites

* On Linux or {mac}, ensure that your user account has permission to use the [command]`sudo` command.
On {msw}, ensure that your user account can elevate to Administrator privileges.

[NOTE]
====
Do not run the [command]`{bin}` executable as the `root` user or an administrator.
Always run the [command]`{bin}` executable with your user account.
====

.Procedure

. Set up your host machine for {prod}:
+
[subs="+quotes,attributes"]
----
$ {bin} setup
----

.Consent for telemetry data collection

The `{bin} setup` command prompts you for optional, anonymous usage data collection to assist with development.
No personally identifiable information is collected.

* To manually enable telemetry, run the following command:
+
[subs="+quotes,attributes"]
----
$ {bin} config set consent-telemetry yes
----

* To manually disable telemetry, run the following command:
+
[subs="+quotes,attributes"]
----
$ {bin} config set consent-telemetry no
----

For more information about collected data, see the Red{nbsp}Hat link:https://developers.redhat.com/article/tool-data-collection[Telemetry data collection notice].
