[id="accessing-the-openshift-cluster-with-oc_{context}"]
= Accessing the OpenShift cluster with `oc`

.Prerequisites

* A running {prod} virtual machine.
For more information, see link:{crc-gsg-url}#starting-the-virtual-machine_gsg[Starting the virtual machine].

.Procedure

To access the OpenShift cluster through the [command]`oc` command, follow these steps:

. Run the [command]`{bin} oc-env` command to print the command needed to add the cached [command]`oc` executable to your `_PATH_`:
+
[subs="+quotes,attributes"]
----
$ {bin} oc-env
----

. Run the printed command.

. Log in as the `developer` user:
+
[subs="+quotes,attributes"]
----
$ oc login -u developer https://api.crc.testing:6443
----
+
[NOTE]
====
The [command]`{bin} start` command prints the password for the `developer` user.
You can also view it by running the [command]`{bin} console --credentials` command.
====

. You can now use [command]`oc` to interact with your OpenShift cluster.
For example, to verify that the OpenShift cluster Operators are available:
+
[subs="+quotes,attributes",options="nowrap"]
----
$ oc get co
----
+
[NOTE]
====
* {prod} disables the `machine-config` and `monitoring` Operators by default.
====

See link:{crc-gsg-url}#troubleshooting-codeready-containers_gsg[Troubleshooting {prod}] if you cannot access the {prod} OpenShift cluster.

.Additional resources

* The link:https://docs.openshift.com/container-platform/latest/applications/projects/working-with-projects.html[OpenShift documentation] covers the creation of projects and applications.
