[id="starting-monitoring-alerting-telemetry_{context}"]
= Starting monitoring, alerting, and telemetry

{prod} disables cluster monitoring by default to ensure that {prod} can run on a typical notebook.
Telemetry is responsible for listing your cluster in the link:https://console.redhat.com/openshift[Red Hat Hybrid Cloud Console].
Follow this procedure to enable monitoring for your cluster.

.Prerequisites

* You must assign additional memory to the {prod} virtual machine.
At least 14 GiB of memory, a value of `14336`, is recommended for core functionality.
Increased workloads will require more memory.
For more information, see link:{crc-gsg-url}#configuring-the-virtual-machine_gsg[Configuring the virtual machine].

.Procedure

. Set the `enable-cluster-monitoring` configurable property to `true`:
+
[subs="+quotes,attributes"]
----
$ {bin} config set enable-cluster-monitoring true
----

. Start the virtual machine:
+
[subs="+quotes,attributes"]
----
$ {bin} start
----
+
[WARNING]
====
Cluster monitoring cannot be disabled.
To remove monitoring, alerting, and telemetry, set the `enable-cluster-monitoring` configurable property to `false` and delete the existing {prod} virtual machine.
====
