[id="starting-the-virtual-machine_{context}"]
= Starting the virtual machine

The [command]`{bin} start` command starts the {prod} virtual machine and OpenShift cluster.

.Prerequisites

* You set up the host machine through the [command]`{bin} setup` command.
For more information, see <<setting-up-codeready-containers_{context}>>.
* You have a valid OpenShift user pull secret.
Copy or download the pull secret from the Pull Secret section of the link:https://cloud.redhat.com/openshift/install/crc/installer-provisioned[Install on Laptop: {rh-prod}] page on cloud.redhat.com.
+
[NOTE]
====
Accessing the user pull secret requires a Red Hat account.
====

.Procedure

. Start the {prod} virtual machine:
+
[subs="+quotes,attributes"]
----
$ {bin} start
----

. When prompted, supply your user pull secret.

[NOTE]
====
* The cluster takes a minimum of four minutes to start the necessary containers and Operators before serving a request.
* If you see errors during [command]`{bin} start`, check the <<troubleshooting-codeready-containers_{context}>> section for potential solutions.
====
