[id="troubleshooting-expired-certificates_{context}"]
= Troubleshooting expired certificates

[NOTE]
====
As of the {prod} 1.10.0 release, the certificate renewal process is not working as intended.
Follow this procedure to avoid potential errors due to certificate expiration.
====

The system bundle in each released [command]`{bin}` binary expires 30 days after the release.
This expiration is due to certificates embedded in the OpenShift cluster.
As a result, using an older [command]`{bin}` binary or system bundle can result in an expired certificates error.

Starting from {prod} 1.2.0, the embedded certificates can be automatically renewed by [command]`{bin}`.
The [command]`{bin} start` command triggers the certificate renewal process when needed.
Certificate renewal can add up to five minutes to the start time of the cluster.

.Procedure

To resolve expired certificate errors that cannot be automatically renewed:

. link:{crc-download-url}[Download the latest {prod} release] and place the [command]`{bin}` binary in your `$PATH`.

. Remove the cluster with certificate errors using the [command]`{bin} delete` command:
+
include::snip_crc-delete.adoc[]

. Set up the new release:
+
[subs="+quotes,attributes"]
----
$ {bin} setup
----

. Start the new virtual machine:
+
[subs="+quotes,attributes"]
----
$ {bin} start
----
