[id="configuring-the-virtual-machine_{context}"]
= Configuring the virtual machine

Use the `cpus` and `memory` properties to configure the default number of vCPUs and amount of memory available to the {prod} virtual machine, respectively.

Alternatively, the number of vCPUs and amount of memory can be assigned using the `--cpus` and `--memory` flags to the `{bin} start` command, respectively.

[IMPORTANT]
====
You cannot change the configuration of a running {prod} virtual machine.
To enable configuration changes, you must stop the running virtual machine and start it again.
====

.Procedure

* To configure the number of vCPUs available to the virtual machine:
+
[subs="+quotes,attributes"]
----
$ {bin} config set cpus __<number>__
----
+
The default value for the `cpus` property is `4`.
The number of vCPUs to assign must be greater than or equal to the default.

* To start the virtual machine with the desired number of vCPUs:
+
[subs="+quotes,attributes"]
----
$ {bin} start --cpus __<number>__
----

* To configure the memory available to the virtual machine:
+
[subs="+quotes,attributes"]
----
$ {bin} config set memory __<number-in-mib>__
----
+
[NOTE]
====
Values for available memory are set in mebibytes (MiB).
One gibibyte (GiB) of memory is equal to 1024 MiB.
====
+
The default value for the `memory` property is `9216`.
The amount of memory to assign must be greater than or equal to the default.

* To start the virtual machine with the desired amount of memory:
+
[subs="+quotes,attributes"]
----
$ {bin} start --memory __<number-in-mib>__
----
