[id="troubleshooting-expired-certificates_{context}"]
= Troubleshooting expired certificates

The system bundle in each released [command]`{bin}` executable expires 30 days after the release.
This expiration is due to certificates embedded in the OpenShift cluster.
The [command]`{bin} start` command triggers an automatic certificate renewal process when needed.
Certificate renewal can add up to five minutes to the start time of the cluster.

To avoid this additional startup time, or in case of failures in the certificate renewal process, use the following procedure:

.Procedure

To resolve expired certificate errors that cannot be automatically renewed:

. link:{crc-download-url}[Download the latest {prod} release] and place the [command]`{bin}` executable in your `$PATH`.

. Remove the cluster with certificate errors using the [command]`{bin} delete` command:
+
include::snip_crc-delete.adoc[]

. Set up the new release:
+
[subs="+quotes,attributes"]
----
$ {bin} setup
----

. Start the new virtual machine:
+
[subs="+quotes,attributes"]
----
$ {bin} start
----
