[id="starting-monitoring-alerting-telemetry_{context}"]
= Starting Monitoring, Alerting, and Telemetry

To make sure {prod} can run on a typical laptop, some resource-heavy services get disabled by default.
One of these is Prometheus and the related monitoring, alerting, and telemetry functionality.
Telemetry functionality is responsible for listing your cluster in the link:https://cloud.redhat.com/openshift[Red Hat OpenShift Cluster Manager].

.Prerequisites

* A running {prod} virtual machine and a working [command]`oc` command.
For more information, see link:{crc-gsg-url}#accessing-the-openshift-cluster-with-oc_gsg[Accessing the OpenShift cluster with `oc`].
* You must log in through [command]`oc` as the `kubeadmin` user.
* You must assign additional memory to the {prod} virtual machine.
At least 14 GiB of memory (a value of `14336`) is recommended for core functionality. 
Increased workloads will require more memory.
For more information, see link:{crc-gsg-url}#configuring-the-virtual-machine_gsg[Configuring the virtual machine].

.Procedure

. List unmanaged Operators and note the numeric index for `cluster-monitoring-operator`:

** On Linux or {mac}:
+
[subs="+quotes"]
----
$ oc get clusterversion version -ojsonpath='{range .spec.overrides[*]}{.name}{"\n"}{end}' | nl -v 0
----

** On {msw} using PowerShell:
+
[subs="+quotes"]
----
PS> oc get clusterversion version -ojsonpath='{range .spec.overrides[*]}{.name}{\"\n\"}{end}' | % {$nl++;"`t$($nl-1) `t $_"};$nl=0
----

. Start monitoring, alerting, and telemetry services using the identified numeric index for `cluster-monitoring-operator`:

** On Linux or {mac}:
+
[subs="+quotes"]
----
$ oc patch clusterversion/version --type='json' -p '[{"op":"remove", "path":"/spec/overrides/_<cluster-monitoring-operator-index>_"}]'
clusterversion.config.openshift.io/version patched
----

** On {msw} using PowerShell:
+
[subs="+quotes"]
----
PS> oc patch clusterversion/version --type='json' -p '[{\"op\":\"remove\", \"path\":\"/spec/overrides/_<cluster-monitoring-operator-index>_\"}]'
----
