[id="starting-monitoring-alerting-telemetry_{context}"]
= Starting Monitoring, Alerting, and Telemetry

To make sure {prod} can run on a typical laptop, some resource-heavy services get disabled by default.
One of these is Prometheus and the related monitoring, alerting, and telemetry functionality.
Telemetry functionality is responsible for listing your cluster in the link:https://cloud.redhat.com/openshift[Red Hat OpenShift Cluster Manager].

.Prerequisites

* You must assign additional memory to the {prod} virtual machine.
At least 14 GiB of memory (a value of `14336`) is recommended for core functionality. 
Increased workloads will require more memory.
For more information, see link:{crc-gsg-url}#configuring-the-virtual-machine_gsg[Configuring the virtual machine].

.Procedure

. Set the `enable-cluster-monitoring` configurable property to `true`:
+
[subs="+quotes,attributes"]
----
$ {bin} config set enable-cluster-monitoring true
----

. Start the virtual machine:
+
[subs="+quotes,attributes"]
----
$ {bin} start
----
+
[WARNING]
====
Cluster monitoring cannot be disabled.
To remove monitoring, alerting, and telemetry, set the `enable-cluster-monitoring` configurable property to `false` and delete the existing {prod} virtual machine.
====
