[id="troubleshooting-unknown-issues_{context}"]
= Troubleshooting unknown issues

Resolve most issues by restarting {prod} with a clean state.
This involves stopping the virtual machine, deleting it, reverting changes made by the [command]`{bin} setup` command, reapplying those changes, and restarting the virtual machine.

.Prerequisites

* You set up the host machine through the [command]`{bin} setup` command.
For more information, see <<setting-up-codeready-containers_{context}>>.
* You started {prod} through the [command]`{bin} start` command.
For more information, see <<starting-the-virtual-machine_{context}>>.
* You are using the latest {prod} release.
Using a version earlier than {prod} 1.2.0 may result in errors related to expired x509 certificates.
For more information, see <<troubleshooting-expired-certificates_{context}>>.

.Procedure

To troubleshoot {prod}, perform the following steps:

. Stop the {prod} virtual machine:
+
[subs="+quotes,attributes"]
----
$ {bin} stop
----

. Delete the {prod} virtual machine:
+
include::snip_crc-delete.adoc[]

. Clean up remaining changes from the [command]`{bin} setup` command:
+
[subs="+quotes,attributes"]
----
$ {bin} cleanup
----
+
[NOTE]
====
The [command]`{bin} cleanup` command removes an existing {prod} virtual machine and reverts changes to DNS entries created by the [command]`{bin} setup` command.
On {mac}, the [command]`{bin} cleanup` command also removes the system tray.
====

. Set up your host machine to reapply the changes:
+
[subs="+quotes,attributes"]
----
$ {bin} setup
----

. Start the {prod} virtual machine:
+
[subs="+quotes,attributes"]
----
$ {bin} start
----
+
[NOTE]
====
The cluster takes a minimum of four minutes to start the necessary containers and Operators before serving a request.
====

If your issue is not resolved by this procedure, perform the following steps:

. link:https://github.com/code-ready/crc/issues[Search open issues] for the issue that you are encountering.
. If no existing issue addresses the encountered issue, link:https://github.com/code-ready/crc/issues/new[create an issue] and link:https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests[attach the [filename]`~/.crc/crc.log` file] to the created issue.
The [filename]`~/.crc/crc.log` file has detailed debugging and troubleshooting information which can help diagnose the problem that you are experiencing.
