[id="dns-configuration_{context}"]
= DNS configuration details

[id="dns-configuration-general{context}"]
== General DNS setup

The OpenShift cluster managed by {prod} uses 2 DNS domain names, `crc.testing` and `apps-crc.testing`.
The `crc.testing` domain is for core OpenShift services.
The `apps-crc.testing` domain is for accessing OpenShift applications deployed on the cluster.

For example, the OpenShift API server will be exposed as `api.crc.testing` while the OpenShift console is accessed through `console-openshift-console.apps-crc.testing`.
These DNS domains are served by a `dnsmasq` DNS container running inside the {prod} virtual machine.

Running [command]`{bin} setup` will detect and adjust your system DNS configuration so that it can resolve these domains.
Additional checks are done to verify DNS is properly configured when running [command]`{bin} start`.

[id="dns-configuration-linux_{context}"]
== Linux

On Linux, depending on your distribution, {prod} expects the following DNS configuration:

=== NetworkManager + systemd-resolved

This configuration is used by default on Fedora 33 or newer, and on Ubuntu Desktop editions.

* {prod} expects NetworkManager to manage networking.
* {prod} configures `systemd-resolved` to forward requests for the `testing` domain to the `192.168.130.11` DNS server.
`192.168.130.11` is the IP of the {prod} virtual machine.
* `systemd-resolved` configuration is done through a NetworkManager dispatcher script in `/etc/NetworkManager/dispatcher.d/99-crc.sh`:
+
----
#!/bin/sh

export LC_ALL=C

systemd-resolve --interface crc --set-dns 192.168.130.11 --set-domain ~testing

exit 0
----

[NOTE]
====
`systemd-resolved` is also available as an unsupported Technology Preview on {rhel} and {centos} 8.3.
After {rhel-resolved-docs}[configuring the host] to use `systemd-resolved`, stop any running clusters and rerun [command]`{bin} setup`.
====

=== NetworkManager + dnsmasq

This configuration is used by default on Fedora 32 or older, on {rhel}, and on {centos}.

* {prod} expects NetworkManager to manage networking.
* NetworkManager uses `dnsmasq` through the [filename]`/etc/NetworkManager/conf.d/crc-nm-dnsmasq.conf` configuration file.
* The configuration file for this `dnsmasq` instance is [filename]`/etc/NetworkManager/dnsmasq.d/crc.conf`:
+
----
server=/crc.testing/192.168.130.11
server=/apps-crc.testing/192.168.130.11
----
** The NetworkManager `dnsmasq` instance forwards requests for the `crc.testing` and `apps-crc.testing` domains to the `192.168.130.11` DNS server.

[id="dns-configuration-mac_{context}"]
== {mac}

On {mac}, {prod} expects the following DNS configuration:

* {prod} creates a [filename]`/etc/resolver/testing` file which instructs {mac} to forward all DNS requests  for the `testing` domain to the {prod} virtual machine.
* {prod} also adds an `api.crc.testing` entry to [filename]`/etc/hosts` pointing at the VM IP address.
The [command]`oc` executable requires this entry.
See https://github.com/openshift/origin/issues/23266[OpenShift issue #23266] for more information.

////
== {msw}

TODO
////
