[id="minimum-system-requirements_{context}"]
= Minimum system requirements

{prod} has the following minimum hardware and operating system requirements.

[id="minimum-system-requirements-hardware_{context}"]
== Hardware requirements

{prod} requires the following system resources:

* 4 physical CPU cores
* 9 GB of free memory
* 35 GB of storage space

{prod} is supported only on AMD64 and Intel 64 processor architectures.
{prod} does not support the ARM-based M1 architecture.

[NOTE]
====
The OpenShift cluster requires these minimum resources to run in the {prod} virtual machine.
Some workloads may require more resources.
To assign more resources to the {prod} virtual machine, see link:{crc-gsg-url}#configuring-the-virtual-machine_gsg[Configuring the virtual machine].
====

[id="minimum-system-requirements-operating-system_{context}"]
== Operating system requirements

{prod} requires the following minimum version of a supported operating system:

=== {msw}

* On {msw}, {prod} requires the Windows 10 Fall Creators Update (version 1709) or newer.
{prod} does not work on earlier versions of {msw}.
{msw} 10 Home Edition is not supported.

=== {mac}

* On {mac}, {prod} requires {mac} 10.14 Mojave or newer.
{prod} does not work on earlier versions of {mac}.

=== Linux

* On Linux, {prod} is only supported on {rhel}/{centos} 7.5 or newer (including 8.x versions) and on the latest two stable {fed} releases.
* When using {rhel}, the machine running {prod} must be link:https://access.redhat.com/solutions/253273[registered with the Red Hat Customer Portal].
* {ubuntu} 18.04 LTS or newer and {debian} 10 or newer are not officially supported and may require manual set up of the host machine.
* See link:{crc-gsg-url}#required-software-packages_gsg[Required software packages] to install the required packages for your Linux distribution.
