= Differences from a production {ocp} installation

The {openshift} preset for {rh-prod} provides a regular {ocp} installation with the following notable differences:

* **The {ocp} cluster is ephemeral and is not intended for production use.**
* **{prod} does not have a supported upgrade path to newer {ocp} versions.**
Upgrading the {ocp} version might cause issues that are difficult to reproduce.
* It uses a single node, which behaves as both a control plane and worker node.
* It disables the Cluster Monitoring Operator by default.
This disabled Operator causes the corresponding part of the web console to be non-functional.
* It disables the following operators:
** Cloud Credential Operator.
** Cluster Autoscaler Operator.
** Cloud Controller Manager Operator.
* The {ocp} cluster runs in a virtual machine known as an __instance__.
This might cause other differences, particularly with external networking.

The {ocp} cluster provided by {prod} also includes the following non-customizable cluster settings.
These settings should not be modified:

* The ***.crc.testing** domain.
* The address range used for internal cluster communication.
** The cluster uses the **172** address range.
This can cause issues when, for example, a proxy is run in the same address space.
