= Troubleshooting unknown issues

Resolve most issues by restarting {prod} with a clean state.
This involves stopping the instance, deleting it, reverting changes made by the [command]`{bin} setup` command, reapplying those changes, and restarting the instance.

.Prerequisites
* You set up the host machine with the [command]`{bin} setup` command.
For more information, see link:{crc-gsg-url}#setting-up_gsg[Setting up {prod}].
* You started {prod} with the [command]`{bin} start` command.
For more information, see link:{crc-gsg-url}#starting-the-instance_gsg[Starting the instance].
* You are using the latest {prod} release.
Using a version earlier than {prod} 1.2.0 might result in errors related to expired x509 certificates.
For more information, see link:{crc-gsg-url}#troubleshooting-expired-certificates_gsg[Troubleshooting expired certificates].

.Procedure
To troubleshoot {prod}, perform the following steps:

. Stop the {prod} instance:
+
[subs="+quotes,attributes"]
----
$ {bin} stop
----

. Delete the {prod} instance:
+
include::partial$snip_crc-delete.adoc[]

. Clean up remaining changes from the [command]`{bin} setup` command:
+
[subs="+quotes,attributes"]
----
$ {bin} cleanup
----
+
[NOTE]
====
The [command]`{bin} cleanup` command removes an existing {prod} instance and reverts changes to DNS entries created by the [command]`{bin} setup` command.
====

. Set up your host machine to reapply the changes:
+
[subs="+quotes,attributes"]
----
$ {bin} setup
----

. Start the {prod} instance:
+
[subs="+quotes,attributes"]
----
$ {bin} start
----
+
[NOTE]
====
The cluster takes a minimum of four minutes to start the necessary containers and Operators before serving a request.
====

If your issue is not resolved by this procedure, perform the following steps:

. link:https://github.com/crc-org/crc/issues[Search open issues] for the issue that you are encountering.
. If no existing issue addresses the encountered issue, link:https://github.com/crc-org/crc/issues/new[create an issue] and link:https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests[attach the [filename]*_~/.crc/crc.log_* file] to the created issue.
The [filename]*_~/.crc/crc.log_* file has detailed debugging and troubleshooting information which can help diagnose the problem that you are experiencing. In case you're looking for more detailed information about virtual machine startup, state transitions and errors you can
look into serial console logs created by virtual machine hypervisors. Here are the locations where you can find these logs:
  - **libvirt**: In case of https://libvirt.org/kbase/debuglogs.html[libvirt], you can find the log file in `/var/log/libvirt/qemu/crc.log`
  - **vfkit**: In case of https://github.com/crc-org/vfkit[vfkit], you can find log file in `~/.crc/vfkit.log`
  - **hyper-v**: In case of Hyper-V, there are several options to get logs:
    * **Event Logs for Hyper-V**: Go to start and open `Event Viewer`, then navigate to `Applications and Services Logs` → `Microsoft` → `Windows`. Here you should be able to find some options for `Hyper-V`,
      click on `Hyper-V-VMMS` for Hyper-V Virtual Machine Management logs and `Hyper-V-Worker` for Hyper-V Worker logs.
    * **VM Configuration Logs**: Each VM has a set of logs that can be found in the VM configuration folder. By default, this is located in the `C:\ProgramData\Microsoft\Windows\Hyper-V` folder. For each VM, there is a file called Virtual Machine Log File (`vmname.evtx`)
      that records the events related to that particular VM.
