= Setting up {prod}

[role="_abstract"]
The [command]`{bin} setup` command performs operations to set up the environment of your host machine for the {prod} instance.

The [command]`{bin} setup` command creates the [filename]*_~/.crc_* directory if it does not already exist.

[WARNING]
====
If you are setting up a new version, capture any changes made to the instance before setting up a new {prod} release.
====

.Prerequisites
* On Linux or {mac}, ensure that your user account has permission to use the [command]`sudo` command.
On {msw}, ensure that your user account can elevate to Administrator privileges.

[NOTE]
====
Do not run the [command]`{bin}` executable as the `root` user or an administrator.
Always run the [command]`{bin}` executable with your user account.
====

.Procedure
. Set up your host machine for {prod}:
+
[subs="+quotes,attributes"]
----
$ {bin} setup
----

[role="_additional-resources"]
.Additional resources
* For more information about the available container runtime presets, see link:{crc-gsg-url}#about-presets_gsg[About presets].
