= Minimum system requirements

[role="_abstract"]
{prod} has the following minimum hardware and operating system requirements.

== Hardware requirements

{prod} is supported on these architectures:

include::example$snip_{project-context}_preset_platforms.adoc[]

{prod} does not support nested virtualization.

Depending on the desired container runtime, {prod} requires the following system resources:

=== For {ocp}

* 4 physical CPU cores
* 9 GB of free memory
* 35 GB of storage space

=== For {ushift}

* 2 physical CPU cores
* 4 GB of free memory
* 35 GB of storage space

[NOTE]
====
The {ocp} and {ushift} presets require these minimum resources to run in the {prod} instance.
Some workloads might require more resources.
To assign more resources to the {prod} instance, see link:{crc-gsg-url}#configuring-the-instance_gsg[Configuring the instance].
====

== Operating system requirements

{prod} requires the following minimum version of a supported operating system:

=== Requirements on {msw}

* On {msw}, {prod} requires fully updated {msw} 10 or {msw} 11.
{prod} does not work on earlier versions of {msw}.
* {prod} does not work on {msw} Home Edition.

=== Requirements on {mac}

* On {mac}, {prod} requires {mac} 12 Monterey or later.
{prod} does not work on earlier versions of {mac}.

=== Requirements on Linux

* On Linux, {prod} is supported only on the latest two {rhel}/{centos} 8 and 9 minor releases and on the latest two stable {fed} releases.
* When using {rhel}, the machine running {prod} must be link:https://access.redhat.com/solutions/253273[registered with the Red Hat Customer Portal].
* {ubuntu} 18.04 LTS or later and {debian} 10 or later are not supported and might require manual set up of the host machine.
* See link:{crc-gsg-url}#required-software-packages_gsg[Required software packages] to install the required packages for your Linux distribution.
