name: Enhancement💡
description: Suggest a enhancement for CRC
labels: [kind/enhancement]

body:
  - type: markdown
    attributes:
      value: |
        🤔  To make it easier for us to help you, please include as much useful information as possible.

        Useful Links:
          - 📄  Documentation: https://crc.dev/docs/introducing/
          - 📝  Contributing: https://crc.dev/engineering-docs/


  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Component
      options:
        - "Documentation"
        - "VM Drivers"
        - "Images"
        - "Daemon"
        - "CLI"
        - "Quality Engineering"
    validations:
      required: false
  - type: textarea
    id: problem
    attributes:
      label: Is your enhancement related to a problem? Please describe
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the enhancement here.
