[id="troubleshooting-expired-certificates_{context}"]
= Troubleshooting expired certificates

Before {rh-prod} 1.2.0, the system bundle in each released [command]`{bin}` binary expired 30 days after the release.
This expiration was due to certificates embedded in the OpenShift cluster.
As a result, using an older [command]`{bin}` binary or system bundle results in an expired certificates error.

Starting from {prod} 1.2.0, the embedded certificates can be automatically renewed by [command]`{bin}`.
The [command]`{bin} start` command triggers the certificate renewal process when needed.
Certificate renewal can add up to five minutes to the start time of the cluster.

.Procedure

With {prod} releases older than 1.2.0, to resolve expired certificate errors:

. link:{crc-download-url}[Download the latest {prod} release] and place the [command]`{bin}` binary in your `$PATH`.

. Remove the cluster with certificate errors using the [command]`{bin} delete` command:
+
include::snip_crc-delete.adoc[]

. Set up the new release:
+
[subs="+quotes,attributes"]
----
$ {bin} setup
----

. Start the new virtual machine:
+
[subs="+quotes,attributes"]
----
$ {bin} start
----
