[id="minimum-system-requirements_{context}"]
= Minimum system requirements

{prod} requires the following minimum hardware and operating system requirements.

[id="minimum-system-requirements-hardware_{context}"]
== Hardware requirements

{prod} requires the following system resources:

* 4 virtual CPUs (vCPUs)
* 8 GB of memory
* 35 GB of storage space

[NOTE]
====
The OpenShift cluster requires these minimum resources to run in the {prod} virtual machine.
Some workloads may require more resources.
====

[id="minimum-system-requirements-operating-system_{context}"]
== Operating system requirements

{prod} requires the following minimum version of a supported operating system:

=== {msw}

* On {msw}, {prod} requires the Windows 10 (Pro or Home) Fall Creators Update (version 1709).
{prod} does not work on earlier versions or editions of {msw}.

=== {mac}

* On {mac}, {prod} requires macOS 10.12 Sierra or newer.
{prod} does not work on earlier versions of {mac}.

=== Linux

* On Linux, {prod} is only supported on {rhel}/{centos} 7.5 or newer (including 8.x versions) and on the latest two stable {fed} releases.
* When using {rhel}, the machine running {prod} must be link:https://access.redhat.com/solutions/253273[registered with the Red Hat Customer Portal].
* {ubuntu} 18.04 LTS or newer and {debian} 10 or newer are not officially supported and may require manual set up of the host machine.
* See <<required-software-packages_{context}>> to install the required packages for your Linux distribution.
