
FROM registry.access.redhat.com/ubi8/go-toolset:1.20 AS builder

USER root

ARG OS 
ARG ARCH
WORKDIR /workspace
COPY . .
RUN GOARCH=${ARCH} GOOS=${OS} make build_integration

FROM quay.io/rhqp/deliverest:v0.0.6

LABEL org.opencontainers.image.authors="CRCQE <devtools-crc-qe@redhat.com>"

ARG OS 
ARG ARCH

ENV ASSETS_FOLDER=/opt/crc \
    OS=${OS} \
    ARCH=${ARCH}

COPY --from=builder /workspace/out/${OS}-${ARCH} ${ASSETS_FOLDER}/bin
COPY images/build-integration/lib/${OS}/* ${ASSETS_FOLDER}/

