[id="understanding-codeready-containers_{context}"]
= Understanding {prod}

{rh-prod} brings a minimal OpenShift 4.0 or newer cluster to your local computer.
This cluster provides a minimal environment for development and testing purposes.
It's mainly targetted at running on developers' desktops.
For other use cases, such as headless, multi-developer/team-based setups, ..., use of the link:https://cloud.redhat.com/openshift/install/[full-fledged OpenShift installer] is recommended.

{prod} includes the [command]`{bin}` command-line interface (CLI) to interact with the {prod} virtual machine running the OpenShift cluster.

= Differences with a production OpenShift install

{rh-prod} is a regular OpenShift installation with the following notable differences:

* It uses a single node which behaves both as a master and as a worker node.
* The `machine-config`, `marketplace` and `monitoring` Operators are disabled by default.
* These disabled Operators will cause the corresponding parts of the web console to be non functional.
* For the same reason, there is currently no upgrade path to newer OpenShift versions.
* Due to technical limitations, the {prod} cluster is ephemeral and will need to be recreated from scratch once a month using a newer release.
* The OpenShift instance is running in a virtual machine, which could cause some other differences, in particular in relation with external networking.
