[id="basic-troubleshooting_{context}"]
= Basic troubleshooting

[NOTE]
====
Each released `crc` binary expires 30 days after the release due to certificates embedded in the Openshift cluster.
Using an older `crc` binary will result in an expired certificates error.

To resolve this error:

* link:https://github.com/code-ready/crc/releases[Download the latest CodeReady Containers release] and place the `crc` binary in your `$PATH`.
* Remove the cluster with certificate errors using the `crc delete` command.
* Set up the new release with the `crc setup` command.
* Start the new cluster with the `crc start` command.

====

The majority of issues can be resolved by stopping a running {prod} virtual machine, deleting the virtual machine, and starting a new instance of the virtual machine.

.Prerequisites

* The host machine has been set up using the [command]`{bin} setup` command.
For more information, see <<setting-up-codeready-containers_{context}>>.
* The virtual machine has been started using the [command]`{bin} start` command.
For more information, see <<starting-the-virtual-machine_{context}>>.

.Procedure

To troubleshoot {prod}, perform the following steps:

. Stop the {prod} virtual machine:
+
[subs="+quotes,attributes"]
----
$ {bin} stop
----

. Delete the {prod} virtual machine:
+
[subs="+quotes,attributes"]
----
$ {bin} delete
----

. Start the {prod} virtual machine:
+
[subs="+quotes,attributes"]
----
$ {bin} start
----
+
[NOTE]
====
The cluster takes a minimum of four minutes to start the necessary containers and operators before serving a request.
====

If your issue has not been resolved by this procedure, perform the following steps:

. link:https://github.com/code-ready/crc/issues[Search open issues] for the issue that you are encountering.
. If no existing issue addresses the encountered issue, link:https://github.com/code-ready/crc/issues/new[create an issue] and link:https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests[attach the [filename]`~/.crc/crc.log` file] to the created issue.
The [filename]`~/.crc/crc.log` file contains detailed debugging and troubleshooting information which can help diagnose the problem that you are experiencing.

= DNS configuration details

This section describes how {prod} configures networking.
This can be useful for troubleshooting, or in case you are using a non-standard DNS setup, and want to adjust it for {prod} needs.
The [command]`{bin} ip` command can be used to obtain the VM IP address as needed.
This address can change each time the VM is restarted.


== Linux

* {prod} expects NetworkManager to be used to manage networking.
* NetworkManager is set up to use dnsmasq through the [filename]`/etc/NetworkManager/conf.d/crc-nm-dnsmasq.conf` configuration file.
* The configuration file for this dnsmasq instance is [filename]`/etc/NetworkManager/dnsmasq.d/crc.conf`:
```
server=/crc.testing/192.168.130.11
server=/apps-crc.testing/192.168.130.11
```
** NetworkManager dnsmasq instance forwards requests for the `crc.testing` and `apps-crc.testing` domains to the 192.168.130.11 DNS server which is a dnsmasq instance running inside the virtual machine.


== {mac}

* {prod} creates a [filename]`/etc/resolver/testing` file which instructs {mac} to forward all DNS requests  for the `testing` domain to the {prod} virtual machine.
* {prod} also adds an `api.crc.testing` entry to [filename]`/etc/hosts` pointing at the VM IP address. This is needed by the `oc` binary, see https://github.com/openshift/origin/issues/23266[OpenShift issue #23266].

////
== {msw}

TODO
////
