[id="accessing-the-openshift-cluster_{context}"]
= Accessing the OpenShift cluster

.Prerequisites

* A running {prod} virtual machine.
For more information, see <<starting-the-virtual-machine_{context}>>.

.Procedure

* To access the OpenShift web console, follow these steps:

  . Run [command]`{bin} console`. This will open your web browser and direct it to the web console.

  . Log in to the OpenShift web console as the `developer` user with the password printed in the output of the [command]`{bin} start` command.
+
[NOTE]
====
You can also view the password for the `developer` user by running [command]`{bin} console --credentials`.
====
+
[NOTE]
====
The cluster can initially be accessed through either the `kubeadmin` or `developer` user.
For creating projects or OpenShift applications, and for application deployment, the `developer` user should be used.
The `kubeadmin` user should only be used for administrative tasks such as creating new users, setting roles, and so on.
====
+
See <<troubleshooting-codeready-containers_{context}>> if you cannot access the {prod} OpenShift cluster.

* To access the OpenShift cluster via the [command]`oc` command, follow these steps:

  . Run the [command]`{bin} oc-env` command to print the command needed to add the cached [command]`oc` binary to your `_PATH_`:
+
[subs="+quotes,attributes"]
----
$ crc oc-env
----

  . Run the printed command.

  . Log in by running the [command]`oc login -u developer https://api.crc.testing:6443` command.
+
[NOTE]
====
The password for the `developer` user was printed in the output of the [command]`{bin} start` command.
You can also view it by running the [command]`{bin} console --credentials` command.
====
+
  . You can now use `oc` to interact with your OpenShift cluster. For example, to verify that the OpenShift cluster operators are available using the [command]`oc get co` command:
+
[subs="+quotes,attributes"]
----
$ oc get co
NAME                                 VERSION      AVAILABLE   PROGRESSING   FAILING   SINCE
authentication                       4.1.0-rc.0   True        False         False     6d6h
cloud-credential                     4.1.0-rc.0   True        False         False     6d6h
cluster-autoscaler                   4.1.0-rc.0   True        False         False     6d6h
console                              4.1.0-rc.0   True        False         False     6d6h
dns                                  4.1.0-rc.0   True        False         False     89m
image-registry                       4.1.0-rc.0   True        False         False     6d6h
ingress                              4.1.0-rc.0   True        False         False     89m
kube-apiserver                       4.1.0-rc.0   True        False                   6d6h
kube-controller-manager              4.1.0-rc.0   True        False                   6d6h
kube-scheduler                       4.1.0-rc.0   True        False                   6d6h
machine-api                          4.1.0-rc.0   True        False         False     6d6h
machine-config                       4.1.0-rc.0   False       False         True      6d6h
marketplace                          4.1.0-rc.0   False       False         True      6d6h
monitoring                                        Unknown     True          Unknown   6d6h
network                              4.1.0-rc.0   True        False                   6d6h
node-tuning                          4.1.0-rc.0   True        False         False     89m
openshift-apiserver                  4.1.0-rc.0   True        False                   6d6h
openshift-controller-manager         4.1.0-rc.0   True        False                   5d11h
openshift-samples                    4.1.0-rc.0   True        False         False     6d6h
operator-lifecycle-manager           4.1.0-rc.0   True        False         False     6d6h
operator-lifecycle-manager-catalog   4.1.0-rc.0   True        False         False     6d6h
service-ca                           4.1.0-rc.0   True        False         False     6d6h
service-catalog-apiserver            4.1.0-rc.0   True        False         False     88m
service-catalog-controller-manager   4.1.0-rc.0   True        False         False     88m
storage                              4.1.0-rc.0   True        False         False     6d6h
----
+
[NOTE]
====
The `machine-config` and `marketplace` cluster operators are expected to report `False` availability.
The `monitoring` cluster operator is expected to report `Unknown` availability.
====
+
See <<troubleshooting-codeready-containers_{context}>> if you cannot access the {prod} OpenShift cluster.
