[id="basic-troubleshooting_{context}"]
= Basic troubleshooting

The majority of issues can be resolved by stopping a running {prod} virtual machine, deleting the virtual machine, and starting a new instance of the virtual machine.

.Prerequisites

* The host machine has been set up using the [command]`{bin} setup` command.
For more information, see <<setting-up-codeready-containers_{context}>>.
* The virtual machine has been started using the [command]`{bin} start` command.
For more information, see <<starting-the-virtual-machine_{context}>>.
* You are using the newest available system image bundle.
The generated certificates for the system image bundle expire after 30 days.
Using an older system image bundle may result in errors related to expired x509 certificates.

.Procedure

To troubleshoot {prod}, perform the following steps:

. Stop the {prod} virtual machine:
+
[subs="+quotes,attributes"]
----
$ {bin} stop
----

. Delete the {prod} virtual machine:
+
[subs="+quotes,attributes"]
----
$ {bin} delete
----

. Start the {prod} virtual machine:
+
[subs="+quotes,attributes"]
----
$ {bin} start -b _path_to_system_bundle_
----
+
[NOTE]
====
The cluster takes a minimum of four minutes to start the necessary containers and operators before serving a request.
====

If your issue has not been resolved by this procedure, perform the following steps:

. link:https://github.com/code-ready/crc/issues[Search open issues] for the issue that you are encountering.
. If no existing issue addresses the encountered issue, link:https://github.com/code-ready/crc/issues/new[create an issue] and link:https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests[attach the [filename]`~/.crc/crc.log` file] to the created issue.
The [filename]`~/.crc/crc.log` file contains detailed debugging and troubleshooting information which can help diagnose the problem that you are experiencing.
