[id="starting-the-virtual-machine_{context}"]
= Starting the virtual machine

The [command]`{bin} start` command starts the {prod} virtual machine and OpenShift cluster.

.Prerequisites

* The host machine has been set up using the [command]`{bin} setup` command.
For more information, see <<setting-up-codeready-containers_{context}>>.
* A valid OpenShift user pull secret.
The pull secret can be copied or downloaded from the Pull Secret section of the link:https://cloud.redhat.com/openshift/install/crc/installer-provisioned[Install on Laptop: Red Hat CodeReady Containers] page on cloud.redhat.com.
+
[NOTE]
====
A Red Hat account is required in order to access the user pull secret.
====

.Procedure

* Start the {prod} virtual machine:

** For native hypervisors:
+
[subs="+quotes,attributes"]
----
$ {bin} start
----

** For VirtualBox, a bundle file downloaded separately and the `--vm-driver virtualbox` and `--bundle` flags are required:
+
[subs="+quotes,attributes"]
----
$ {bin} start --vm-driver virtualbox --bundle _path_to_system_bundle_
----

* When prompted, supply your user pull secret.

[NOTE]
====
The cluster takes a minimum of four minutes to start the necessary containers and operators before serving a request.
====
