name: Test OKD bundle
on:
  push:
    branches: [ main ]
  pull_request: {}
jobs:
  build:
    name: Run OKD bundle with crc
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - '1.20'
    env:
      SHELL: /bin/bash
      KUBECONFIG: '/Users/runner/.kube/config'
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Build
        run: |
          make cross
          sudo cp out/linux-amd64/crc /usr/local/bin/crc

      - name: Install required virtualization software
        run: |
          sudo apt-get update
          sudo apt install qemu-kvm libvirt-daemon libvirt-daemon-system
          sudo usermod -a -G libvirt $USER
      - name: Remove unwanted stuff to free up disk image
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf /opt/hostedtoolcache/CodeQL

          sudo docker image prune --all --force

          sudo swapoff -a
          sudo rm -f /mnt/swapfile

      - name: Set the crc config
        run: |
          crc config set preset okd
          crc config set network-mode user
      - name: Setup the crc
        run: sudo -su $USER crc setup
      - name: Start the crc
        run: sudo -su $USER crc start
