name: Verify make cross in devcontainer
on:
  push:
    branches:
      - "main"
  pull_request: {}
jobs:
  verify-devcontainer:
    runs-on: ubuntu-24.04
    container:
      image: registry.ci.openshift.org/openshift/release:rhel-8-release-golang-1.23-openshift-4.19
      options: --cpus 4
    steps:
      - name: Run `git clone`
        run: git clone https://github.com/crc-org/crc --depth 1
      - name: Run `make cross`
        run: |
          cd crc
          make cross
