name: Verify make cross in devcontainer
on:
  push:
    branches:
      - "main"
  pull_request: {}
jobs:
  verify-devcontainer:
    runs-on: ubuntu-24.04
    container:
      image: registry.access.redhat.com/ubi9/go-toolset:latest
      options: --cpus 4
    steps:
      - name: Run `git clone`
        run: git clone https://github.com/crc-org/crc --depth 1
      - name: Run `make cross`
        run: |
          cd crc
          make cross
